[supervisord]
nodaemon=true

[program:apache]
command=/usr/local/bin/apache2-foreground
autostart=true
autorestart=true
priority=10

[program:arduino]
command=/usr/bin/python3 /opt/oficina/python/arduino_bridge.py
autostart=true
autorestart=true
priority=20