Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/rocky-9"
  config.vm.box_version = "9.4.5"
  # Sistema Operacional
 
  # Hostname
  config.vm.hostname = "app01"

  # Rede privada (padrão do lab)
  config.vm.network "private_network", ip: "192.168.56.12"

  # Redirecionamento de porta
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Provisionamento
  config.vm.provision "shell", path: "provision.sh"
end
