
Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/rocky-9"
  config.vm.box_version = "9.4.5"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.15"
  config.vm.synced_folder ".", "/vagrant", 
    type: "nfs", 
    nfs_version: 4, 
    mount_options: ["rw", "tcp", "nolock"]
  config.vm.provision "shell", path: "provision.sh" 
end
