Vagrant.configure("2") do |config|
    config.vm.box = "eurolinux-vagrant/rocky-9"
    config.vm.box_version = "9.4.5"
    config.vm.hostname = "db01"
    config.vm.network "private_network", ip: "192.168.56.13"
    config.vm.network "forwarded_port", guest: 3306, host: 13306
    config.vm.provision "shell", path: "provision.sh"
  end
